<a href="https://colab.research.google.com/github/Davron030901/Scikit_learning/blob/main/A_Comprehensive_Guide_to_Cross_Validation_with_Scikit_Learn_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(42)

In [ ]:
fastball_speed=np.random.randint(96,106,size=500)

In [ ]:
tomy_john=np.where(fastball_speed>100,np.random.choice([0,1],size=500,p=[0.3,0.7]),0)

In [ ]:
d={
    'fastball_speed':fastball_speed,
    'tomy_john':tomy_john
}

In [ ]:
df=pd.DataFrame(d)

In [ ]:
df

fastball_speed  tomy_john
0               102          0
1                99          0
2               103          1
3               100          0
4               102          1
..              ...        ...
495              96          0
496             102          0
497             102          1
498             104          0
499              98          0

[500 rows x 2 columns]

In [ ]:
X=df[['fastball_speed']]
y=df[['tomy_john']]

#Normal train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=11)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()

In [ ]:
lr.fit(X_train,y_train.values.ravel())

LogisticRegression()

In [ ]:
lr.score(X_test,y_test)

0.7866666666666666

#Test this again

In [ ]:
X2_train,X2_test,y2_train,y2_test=train_test_split(X,y,test_size=0.2,random_state=25)

In [ ]:
lr.fit(X2_train,y2_train.values.ravel())

LogisticRegression()

In [ ]:
lr.score(X2_test,y2_test)

0.73

#basic cross val

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cvs=cross_val_score(lr,X,y.values.ravel(),cv=10)

In [ ]:
cvs

array([0.74, 0.82, 0.74, 0.8 , 0.7 , 0.76, 0.84, 0.76, 0.8 , 0.76])

In [ ]:
np.average(cvs)

0.772

In [ ]:
np.std(cvs)

0.04019950248448356

#Define standard kfold

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf=KFold(n_splits=15,shuffle=True,random_state=42)

In [ ]:
kfscore=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='f1')

In [ ]:
kfscore2=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='accuracy')

In [ ]:
kfscore

array([0.5       , 0.57142857, 0.82758621, 0.59259259, 0.66666667,
       0.33333333, 0.66666667, 0.75      , 0.33333333, 0.8125    ,
       0.66666667, 0.63636364, 0.54545455, 0.69565217, 0.70588235])

In [ ]:
np.average(kfscore)

0.6202751164171189

In [ ]:
np.std(kfscore)

0.1424477003100013

In [ ]:
kfscore2

array([0.70588235, 0.73529412, 0.85294118, 0.67647059, 0.73529412,
       0.63636364, 0.78787879, 0.81818182, 0.75757576, 0.81818182,
       0.81818182, 0.75757576, 0.84848485, 0.78787879, 0.84848485])

In [ ]:
np.average(kfscore2)

0.7723113487819369

In [ ]:
np.std(kfscore2)

0.06332868382050484

#stratified K Fold

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
kf3=StratifiedKFold(n_splits=10,shuffle=True,random_state=11)

In [ ]:
kfscore3=cross_val_score(lr,X,y.values.ravel(),cv=kf3)

In [ ]:
kfscore3

array([0.76, 0.84, 0.68, 0.86, 0.74, 0.82, 0.78, 0.72, 0.76, 0.76])

In [ ]:
np.average(kfscore3)

0.772

In [ ]:
np.std(kfscore3)

0.052306787322488064

#pipeline example!

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
from sklearn.pipeline import make_pipeline

In [ ]:
pipe1=make_pipeline(scaler,lr)

In [ ]:
pipe1.fit(X_train,y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [ ]:
scorepipe=cross_val_score(pipe1,X,y.values.ravel(),cv=10)

In [ ]:
scorepipe

array([0.74, 0.82, 0.74, 0.8 , 0.7 , 0.76, 0.84, 0.76, 0.8 , 0.76])

In [ ]:
np.average(scorepipe)

0.772

In [ ]:
np.std(scorepipe)

0.04019950248448356